### PR TITLE
Improved breakpoint management

### PR DESCRIPTION
**Pull request by codecontemplator**
Keep track of breakpoints when disconnected from node so that the user does not need to set them up for each debug session.

### CODE REVIEW

**Comment by codecontemplator** [comment]
@kiddkai I have removed some code from the old addBreakpoint method that appeared dead. During my tests the debugger still works but I might have missed some scenario that I did not know about.

**Comment by codecontemplator** [comment]
Might have a problem with leaked event listeners. Start/stop debugging a couple of times and the following is logged:

```
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
```

Should look at this before merging.

**Comment by kiddkai** [comment]
It do have that issue, I think we can add the remove listeners logic to the `cleanup` method?

**Comment by codecontemplator** [comment]
@kiddkai I have implemented some subscription cleanup. When running some tests on the old code I realized that the problem existed in before this change as well and I have not fixed all of the subscription cleanup problems but I think the code is slightly better now than before... I hope... :)

What has changed in the last commit:
* Added code that decorates the EventEmitter with some utitlity methods for unsubscription
* Using the utility functions in the new class BreakpointManager as well as in the plugin module.

**Pull request merged**
